version: '3.8'

services:
  inventory-db:
    image: postgres:15
    container_name: Inventory.Db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Password123!
      POSTGRES_DB: inventory
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db
  inventory-mb:
    image: rabbitmq:3-management
    container_name: Inventory.RabbitMq
    hostname: inventory-mq
    ports:
      - "5672:5672"
      - "15672-15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - rabbitmq_net
volumes:
  rabbitmq_data:
  postgres_data:
networks:
  rabbitmq_net:
  db: