version: '3.8'

services:
  inventory-mb:
    image: rabbitmq:3-management
    container_name: Inventory.RabbitMq
    hostname: inventory-mq
    ports:
      - "5672:5672"
      - "15672-15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - rabbitmq_net
volumes:
  rabbitmq_data:
networks:
  rabbitmq_net: